---
title: "Chicago Crime Analysis"
output: 
  html_document: 
    fig_height: 7
    fig_width: 10
    theme: sandstone
    toc: yes
runtime: shiny
---
## Library Import 
```{r, echo=FALSE}
library(data.table)
library(DT)
```

## Data Import 
```{r} 

skipColumns <- c(NULL,NULL,"character" ,"character", "character","numeric", "factor", "character", "character", 
                            "character", "character", "numeric","numeric",
                            "numeric", "numeric", "factor", NULL, NULL, "factor",
                            NULL, "numeric", "numeric", NULL)

# chicago 2001 to 2004
chicago2001_2004 <- data.table(read.csv("/home/milan/Documents/MachineLearning/R-workspace/Kaggle/Crimes-in-Chicago/data/Chicago_Crimes_2001_to_2004.csv", quote = "",colClasses=))
# chicago 2005 to 2007
chicago2005_2007 <- fread("/home/milan/Documents/MachineLearning/R-workspace/Kaggle/Crimes-in-Chicago/data/Chicago_Crimes_2005_to_2007.csv",select=c(3:14,19,21,22))
# chicago 2008 to 2011
chicago2008_2011 <- data.table(read.csv("/home/milan/Documents/MachineLearning/R-workspace/Kaggle/Crimes-in-Chicago/data/Chicago_Crimes_2008_to_2011.csv", quote = ""))
# chicago 2012 to 2017
chicago2012_2017 <- data.table(read.csv("/home/milan/Documents/MachineLearning/R-workspace/Kaggle/Crimes-in-Chicago/data/Chicago_Crimes_2012_to_2017.csv", quote = ""))
```

##Sample DataSets
```{r, echo=FALSE, message=FALSE, warning=FALSE}
datatable(head(chicago2001_2004,15))

```




```{r, echo=FALSE}
selectInput("data", "", 
c("co2", "lh")) 


renderPlot({ 
  d <- get(input$data) 
  plot(d) 
}) 
```



